spring:
  application:
    name: Order Service
    version: ${version}
  main:
    lazy-initialization: true

server:
  port: 4080


## Make sure actuator endpoints are secured
management:
  endpoints:
    web:
      exposure:
        include: health,info
