spring:
  profiles:
    default: local
  application:
    name: Inventory Service
    version: ${version}
    description: |
      Inventory service is responsible for blocking inventory for shipping.
      If order processing fails for any reason then this service can be used to release those blocked inventory.
  main:
    lazy-initialization: true

server:
  port: 5080
